branch-defaults:
  default:
    environment: ssm-backend-prod
    group_suffix: null
environment-defaults:
  SectionStockMarket-env:
    branch: null
    repository: null
global:
  application_name: Section Stock Market
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 22 running on 64bit Amazon Linux 2023
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
