-- PostgreSQL schema for SSM on AWS RDS
-- Run once against a fresh database:
--   psql "postgresql://USER:PASSWORD@YOUR-RDS-ENDPOINT:5432/DB_NAME" -f server/schema.sql

begin;

-- ---------------------------------------------------------------------------
-- Extensions
-- ---------------------------------------------------------------------------

create extension if not exists pgcrypto;

-- ---------------------------------------------------------------------------
-- Utility trigger function
-- ---------------------------------------------------------------------------

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

-- ---------------------------------------------------------------------------
-- Helper: derive a deterministic asset_id from a profile
-- ---------------------------------------------------------------------------

create or replace function public.make_asset_id(profile_id uuid, username text)
returns text
language sql
immutable
as $$
  select concat(
    coalesce(nullif(regexp_replace(lower(trim(username)), '[^a-z0-9]+', '-', 'g'), ''), 'user'),
    '-',
    left(replace(profile_id::text, '-', ''), 8),
    '-stock'
  );
$$;

-- ---------------------------------------------------------------------------
-- Tables
-- ---------------------------------------------------------------------------

create table if not exists public.profiles (
  id          uuid        primary key default gen_random_uuid(),
  username    text        not null check (char_length(trim(username)) > 0),
  email       text,
  avatar_url  text,
  deleted_at  timestamptz,
  created_at  timestamptz not null default timezone('utc', now()),
  updated_at  timestamptz not null default timezone('utc', now())
);

create unique index if not exists profiles_username_lower_idx
  on public.profiles (lower(username));

create unique index if not exists profiles_email_idx
  on public.profiles (email)
  where email is not null;

create table if not exists public.user_accounts (
  auth_user_id          uuid    primary key references public.profiles (id) on delete cascade,
  cash_cents            bigint  not null default 0 check (cash_cents >= 0),
  reserved_cash_cents   bigint  not null default 0 check (reserved_cash_cents >= 0),
  created_at            timestamptz not null default timezone('utc', now()),
  updated_at            timestamptz not null default timezone('utc', now())
);

create table if not exists public.assets (
  asset_id            text    primary key,
  issuer_auth_user_id uuid    not null references public.profiles (id) on delete restrict,
  total_supply        bigint  not null check (total_supply > 0),
  name                text,
  created_at          timestamptz not null default timezone('utc', now()),
  updated_at          timestamptz not null default timezone('utc', now())
);

create table if not exists public.holdings (
  auth_user_id    uuid    not null references public.profiles (id) on delete cascade,
  asset_id        text    not null references public.assets (asset_id) on delete cascade,
  shares          bigint  not null default 0 check (shares >= 0),
  reserved_shares bigint  not null default 0 check (reserved_shares >= 0),
  created_at      timestamptz not null default timezone('utc', now()),
  updated_at      timestamptz not null default timezone('utc', now()),
  primary key (auth_user_id, asset_id)
);

create table if not exists public.events (
  id         bigint  generated by default as identity primary key,
  ts_seq     bigint  not null,
  type       text    not null,
  data       jsonb   not null,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists events_ts_seq_idx on public.events (ts_seq, id);

create table if not exists public.orders (
  id                bigint  primary key,
  auth_user_id      uuid    not null references public.profiles (id) on delete cascade,
  asset_id          text    not null references public.assets (asset_id) on delete restrict,
  side              text    not null check (side in ('BUY', 'SELL')),
  qty               bigint  not null check (qty > 0),
  remaining_qty     bigint  not null check (remaining_qty >= 0 and remaining_qty <= qty),
  limit_price_cents bigint  not null check (limit_price_cents > 0),
  status            text    not null,
  seq               bigint  not null,
  created_at        timestamptz not null default timezone('utc', now()),
  updated_at        timestamptz not null default timezone('utc', now())
);

create index if not exists orders_auth_user_seq_idx on public.orders (auth_user_id, seq desc);
create index if not exists orders_asset_seq_idx     on public.orders (asset_id, seq desc);

create table if not exists public.trades (
  id                    bigint  primary key,
  ts_seq                bigint  not null,
  asset_id              text    not null references public.assets (asset_id) on delete restrict,
  price_cents           bigint  not null check (price_cents > 0),
  qty                   bigint  not null check (qty > 0),
  buy_order_id          bigint  not null references public.orders (id) on delete restrict,
  sell_order_id         bigint  not null references public.orders (id) on delete restrict,
  buyer_auth_user_id    uuid    not null references public.profiles (id) on delete restrict,
  seller_auth_user_id   uuid    not null references public.profiles (id) on delete restrict,
  created_at            timestamptz not null default timezone('utc', now())
);

create index if not exists trades_asset_ts_seq_idx on public.trades (asset_id, ts_seq desc);
create index if not exists trades_buyer_idx        on public.trades (buyer_auth_user_id, ts_seq desc);
create index if not exists trades_seller_idx       on public.trades (seller_auth_user_id, ts_seq desc);

create table if not exists public.market_snapshots (
  id         integer     primary key,
  snapshot   jsonb       not null,
  updated_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Business-logic functions
-- ---------------------------------------------------------------------------

create or replace function public.ensure_initial_market_state_for_user(profile_id uuid)
returns void
language plpgsql
as $$
declare
  profile_row public.profiles%rowtype;
  next_asset_id text;
begin
  select *
  into profile_row
  from public.profiles
  where id = profile_id;

  if not found or profile_row.deleted_at is not null then
    return;
  end if;

  insert into public.user_accounts (auth_user_id, cash_cents, reserved_cash_cents)
  values (profile_row.id, 500000, 0)
  on conflict (auth_user_id) do update
  set cash_cents = greatest(public.user_accounts.cash_cents, 500000),
      reserved_cash_cents = public.user_accounts.reserved_cash_cents,
      updated_at = timezone('utc', now());

  select a.asset_id
  into next_asset_id
  from public.assets a
  where a.issuer_auth_user_id = profile_row.id
  order by
    case
      when a.asset_id = public.make_asset_id(profile_row.id, profile_row.username) then 0
      else 1
    end,
    a.created_at asc
  limit 1;

  if next_asset_id is null then
    next_asset_id := public.make_asset_id(profile_row.id, profile_row.username);

    insert into public.assets (asset_id, issuer_auth_user_id, total_supply, name)
    values (next_asset_id, profile_row.id, 1000, concat(profile_row.username, '''s asset'))
    on conflict (asset_id) do nothing;
  else
    update public.assets
    set total_supply = greatest(total_supply, 1000),
        name = coalesce(name, concat(profile_row.username, '''s asset')),
        updated_at = timezone('utc', now())
    where asset_id = next_asset_id;
  end if;

  insert into public.holdings (auth_user_id, asset_id, shares, reserved_shares)
  values (profile_row.id, next_asset_id, 400, 0)
  on conflict (auth_user_id, asset_id) do update
  set shares = greatest(public.holdings.shares, 400),
      reserved_shares = public.holdings.reserved_shares,
      updated_at = timezone('utc', now());
end;
$$;

-- ---------------------------------------------------------------------------
-- Triggers
-- ---------------------------------------------------------------------------

drop trigger if exists set_profiles_updated_at on public.profiles;
create trigger set_profiles_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists set_user_accounts_updated_at on public.user_accounts;
create trigger set_user_accounts_updated_at
before update on public.user_accounts
for each row execute function public.set_updated_at();

drop trigger if exists set_assets_updated_at on public.assets;
create trigger set_assets_updated_at
before update on public.assets
for each row execute function public.set_updated_at();

drop trigger if exists set_holdings_updated_at on public.holdings;
create trigger set_holdings_updated_at
before update on public.holdings
for each row execute function public.set_updated_at();

drop trigger if exists set_orders_updated_at on public.orders;
create trigger set_orders_updated_at
before update on public.orders
for each row execute function public.set_updated_at();

commit;
