begin;

create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  username text not null check (char_length(trim(username)) > 0),
  email text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists profiles_username_lower_idx
  on public.profiles (lower(username));

create or replace function public.handle_auth_user_upsert()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  next_username text;
begin
  next_username := nullif(trim(coalesce(new.raw_user_meta_data ->> 'username', '')), '');

  if next_username is null then
    next_username := split_part(coalesce(new.email, new.id::text), '@', 1);
  end if;

  insert into public.profiles (id, username, email)
  values (new.id, next_username, new.email)
  on conflict (id) do update
  set username = excluded.username,
      email = excluded.email,
      updated_at = timezone('utc', now());

  insert into public.user_accounts (auth_user_id)
  values (new.id)
  on conflict (auth_user_id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert or update on auth.users
for each row execute function public.handle_auth_user_upsert();

create table if not exists public.user_accounts (
  auth_user_id uuid primary key references public.profiles (id) on delete cascade,
  cash_cents bigint not null default 0 check (cash_cents >= 0),
  reserved_cash_cents bigint not null default 0 check (reserved_cash_cents >= 0),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.assets (
  asset_id text primary key,
  issuer_auth_user_id uuid not null references public.profiles (id) on delete restrict,
  total_supply bigint not null check (total_supply > 0),
  name text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.holdings (
  auth_user_id uuid not null references public.profiles (id) on delete cascade,
  asset_id text not null references public.assets (asset_id) on delete cascade,
  shares bigint not null default 0 check (shares >= 0),
  reserved_shares bigint not null default 0 check (reserved_shares >= 0),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  primary key (auth_user_id, asset_id)
);

create table if not exists public.events (
  id bigint generated by default as identity primary key,
  ts_seq bigint not null,
  type text not null,
  data jsonb not null,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists events_ts_seq_idx on public.events (ts_seq, id);

create table if not exists public.orders (
  id bigint primary key,
  auth_user_id uuid not null references public.profiles (id) on delete cascade,
  asset_id text not null references public.assets (asset_id) on delete restrict,
  side text not null check (side in ('BUY', 'SELL')),
  qty bigint not null check (qty > 0),
  remaining_qty bigint not null check (remaining_qty >= 0 and remaining_qty <= qty),
  limit_price_cents bigint not null check (limit_price_cents > 0),
  status text not null,
  seq bigint not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists orders_auth_user_seq_idx on public.orders (auth_user_id, seq desc);
create index if not exists orders_asset_seq_idx on public.orders (asset_id, seq desc);

create table if not exists public.trades (
  id bigint primary key,
  ts_seq bigint not null,
  asset_id text not null references public.assets (asset_id) on delete restrict,
  price_cents bigint not null check (price_cents > 0),
  qty bigint not null check (qty > 0),
  buy_order_id bigint not null references public.orders (id) on delete restrict,
  sell_order_id bigint not null references public.orders (id) on delete restrict,
  buyer_auth_user_id uuid not null references public.profiles (id) on delete restrict,
  seller_auth_user_id uuid not null references public.profiles (id) on delete restrict,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists trades_asset_ts_seq_idx on public.trades (asset_id, ts_seq desc);
create index if not exists trades_buyer_idx on public.trades (buyer_auth_user_id, ts_seq desc);
create index if not exists trades_seller_idx on public.trades (seller_auth_user_id, ts_seq desc);

insert into public.profiles (id, username, email)
select
  u.id,
  coalesce(
    nullif(trim(u.raw_user_meta_data ->> 'username'), ''),
    split_part(coalesce(u.email, u.id::text), '@', 1)
  ),
  u.email
from auth.users u
on conflict (id) do update
set username = excluded.username,
    email = excluded.email,
    updated_at = timezone('utc', now());

insert into public.user_accounts (auth_user_id)
select p.id
from public.profiles p
on conflict (auth_user_id) do nothing;

drop trigger if exists set_profiles_updated_at on public.profiles;
create trigger set_profiles_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists set_user_accounts_updated_at on public.user_accounts;
create trigger set_user_accounts_updated_at
before update on public.user_accounts
for each row execute function public.set_updated_at();

drop trigger if exists set_assets_updated_at on public.assets;
create trigger set_assets_updated_at
before update on public.assets
for each row execute function public.set_updated_at();

drop trigger if exists set_holdings_updated_at on public.holdings;
create trigger set_holdings_updated_at
before update on public.holdings
for each row execute function public.set_updated_at();

drop trigger if exists set_orders_updated_at on public.orders;
create trigger set_orders_updated_at
before update on public.orders
for each row execute function public.set_updated_at();

alter table public.profiles enable row level security;
alter table public.user_accounts enable row level security;
alter table public.assets enable row level security;
alter table public.holdings enable row level security;
alter table public.orders enable row level security;
alter table public.trades enable row level security;
alter table public.events enable row level security;

drop policy if exists "profiles_select_self" on public.profiles;
create policy "profiles_select_self"
on public.profiles
for select
to authenticated
using (auth.uid() = id);

drop policy if exists "profiles_update_self" on public.profiles;
create policy "profiles_update_self"
on public.profiles
for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists "accounts_select_self" on public.user_accounts;
create policy "accounts_select_self"
on public.user_accounts
for select
to authenticated
using (auth.uid() = auth_user_id);

drop policy if exists "assets_select_authenticated" on public.assets;
create policy "assets_select_authenticated"
on public.assets
for select
to authenticated
using (true);

drop policy if exists "holdings_select_self" on public.holdings;
create policy "holdings_select_self"
on public.holdings
for select
to authenticated
using (auth.uid() = auth_user_id);

drop policy if exists "orders_select_self" on public.orders;
create policy "orders_select_self"
on public.orders
for select
to authenticated
using (auth.uid() = auth_user_id);

drop policy if exists "trades_select_authenticated" on public.trades;
create policy "trades_select_authenticated"
on public.trades
for select
to authenticated
using (true);

commit;
